
[[systems]]
  Name = "t01"
  Usage = "production"
  Tags = []
  Lang = "en"
  User = "user1"
  Client = "100"
  Server = "host1.example.com"
  Sysnr = "01"

[[metrics]]
  Name = "sap_users"
  Help = "sm04 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "TH_USER_LIST"
  AllServers = true
  [metrics.tabledata]
    Table = "USRLIST"
    [metrics.tableData.rowcount]
      guiversion = ["76", "75", "74"]
      mandt = ["000", "090", "100", "400"]
      type = [4]

[[metrics]]
  Name = "sap_lock_entries"
  Help = "sm12 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "ENQUE_READ"
  AllServers = false
  [metrics.params]
    GARG = ""
    GCLIENT = ""
    GNAME = ""
    GUNAME = ""
  [metrics.tabledata]
    Table = "ENQ"
    [metrics.tableData.rowcount]
      gclient = ["total", "000", "090", "100", "400"]

[[metrics]]
  Name = "sap_processes"
  Help = "sm50 help"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "TH_WPINFO"
  AllServers = true
  [metrics.params]
    SRVNAME = ""
  [metrics.tabledata]
    Table = "WPLIST"
    [metrics.tableData.rowcount]
      WP_TABLE = ["dbvm", "dbvl", "ma61v", "mdup"]
      WP_TYP = ["dia", "bgd", "upd", "up2", "spo"]
    [metrics.tableData.rowfilter]
      WP_STATUS = ["on hold", "running"]

[[metrics]]
  Name = "sap_stapi_version"
  Help = "SAP ST-A/Pi version info"
  MetricType = "gauge"
  TagFilter = []
  FunctionModule = "ANST_OCS_GET_COMPONENT_STATE"
  AllServers = false
  [metrics.params]
    IV_COMPONENT = "ST-A/PI"
  [metrics.fieldData]
    FieldLabels = ["ev_comp_rel", "ev_comp_spp_level"]

[[metrics]]
  Name = "sap_tune_storage_infos"
  Help = "SAP tune storage infos"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "SAPTUNE_GET_STORAGE_INFOS"
  [metrics.fieldData]
    FieldValues = ["page_bufsz"]

[[metrics]]
  Name = "sap_tune_programs_info"
  Help = "SAP tune buffered programs info"
  MetricType = "gauge"
  TagFilter = []
  AllServers = true
  FunctionModule = "SAPTUNE_BUFFERED_PROGRAMS_INFO"
  [metrics.structureData]
    ExportStructure = "INFO"
    StructureFields = ["coll_ratio","prg_swap", "prg_gen"]
